{% set name = "opencensus-proto" %}
{% set version = "0.1.0" %}
{% set sha256 = "963e4524fef4596482581d3cff0943f68839c7c33a56cdf20967672175ed25bc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: 
    - echo "__version__ = '{{ version }}'" > version.py
    - {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - grpcio >=1.0.0,<2.0.0

test:
  imports:
    - opencensus
    - opencensus.proto
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/census-instrumentation/opencensus-proto
  summary: OpenCensus Proto - Language Independent Interface Types For OpenCensus
  license: Apache-2.0
  license_type: Apache
  license_file: LICENSE
  description: |
    Census provides a framework to define and collect stats against metrics and to
    break those stats down across user-defined dimensions.

    The Census framework is natively available in many languages (e.g. C++, Go,
    and Java). The API interface types are defined using protos to ensure
    consistency and interoperability for the different implementations.
  doc_url: https://github.com/census-instrumentation/opencensus-proto/blob/master/README.md
  doc_source_url: https://github.com/census-instrumentation/opencensus-proto
  dev_url: https://github.com/census-instrumentation/opencensus-proto

extra:
  recipe-maintainers:
    - mariusvniekerk
